name: bookmark_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.4 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  json_serializable: ^6.6.1
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  envied: ^0.3.0
  http: ^0.13.5
  json_annotation: ^4.8.0
  orm: ^3.3.0
